server:
  port: 8072
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
          filters:
            - RewritePath=/resource/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song/**
          filters:
            - RewritePath=/song/(?<path>.*), /$\{path}
    loadbalancer:
      ribbon:
        enabled: false
#    config:
#      enabled: false
gateway:
  service:
    uri: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  config: classpath:logback-spring-local.xml