server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: song-service
          uri: lb://song-service
          predicates:
          - Path=/song/**
          filters:
          - StripPrefix=1
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
          - Path=/license/**
          filters:
          - RewritePath=/license/(?<path>.*), /$\{path}


       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        