server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1

        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka